### PR TITLE
Draft: Maturin, Ceviche Challenges, Local Generator in python, NBDEVv2

### PR DESCRIPTION
**Pull request by jan-david-fischbach**
A bunch of changes:
- Maturin is used to handle compiling the rust generator and binding using pyo3
- A notebook is added that uses Caviche Challenges for the optimization
- A generator that mostly uses local dilations written in python is added (some more work is necessary here to achieve linear scaling with the number of pixels, as in some cases it still falls back to global dilations)
- I migrated to NBDEVv2 (attention the values in `settings.ini` have also been adjusted to work in my fork. We should reset them/not merge the new values. I am however not sure how to do that properly)

### CODE REVIEW

**Comment by jan-david-fischbach** [comment]
@flaport I believe it probably makes more sense If I open separate PRs for the separate features and start cleanly from the current master?

**Comment by jan-david-fischbach** [comment]
Closing in favor of #5 and #6

**Comment by flaport** [comment]
I just bit the bullet and merged everything in this PR manually. I could not do it in the GitHub way because this PR was coming from your master branch and I could not push my changes to your master. But you should be able to merge my master branch cleanly into your master branch now.

Thank you so much for the updates!! 🚀

**Comment by jan-david-fischbach** [comment]
Thanks for the effort!! Sorry, that I created chaos here! I still have a bit of a hard time with nbdev, even though I think it is a wonderful tool (as soon as one is accustomed to it)!

**Pull request closed without merging**
